name: bbr2_model_checking

# --------------------------------------------------
common_parameters:
  send_duration: 100 #s
  truncate_front: 2.0 #s
  truncate_back: 1.0 #s
  plot_load_resolution: 0.01

# --------------------------------------------------
varying_parameters:
  senders: [1]
  link_capacity: [100] # Mbps
  switch_buffer: [0.5] # expressed in BDP of link l
  cc_combination:
    - ['BBR2']
  link_latency: [10] # In ms
  source_latency_range: 
    - [2.5, 5.0]
  qdisc:
    #- RED
    - Drop-tail

# -------------------------------------------------
model_parameters:
  computation_parameters:
    stp: 0.01 #ms
  trace_parameters:
    plot_trace: True
  analysis_parameters:
    analyze: True

# --------------------------------------------------
experiment_parameters:
  pox_directory: [/home/mininet/pox]
  base_config: mininet_experiments/base_config.yaml
  runs: 1

# --------------------------------------------------
plots: 
  B_queueing_cc_combination_droptail:
    model_results: True
    experiment_results: True
    legend: False
    x: switch_buffer
    y: avg_queue
    z: cc_combination
    other:
      senders: 1
      qdisc: Drop-tail
      source_latency_range: [2.5, 5.0]
    dropped_keys:
      x: [0.5]
  

trace_plots:

  trace_droptail:
    model_results: True
    experiment_results: True
    metrics: [x_0, p, q, tau]
    smoothed_metrics: [x_0]
    paper_version: True
    legend: False
    legend_bottom: False
    # focus: True
    legend_keys:
      y: Rate
      x_0: Rate
      q: Queue
      p: Loss
      v_0: Inflight
      whi_0: $w^{\mathrm{hi}}$
      wlo_0: $w^{\mathrm{lo}}$
      mifl_0: $m^{\mathrm{ifl}}$
      tstr_0: Start time
      xmax_0: $x^{\max}$
      xbtl_0: $x^{\mathrm{btl}}$
      xdel_0: $x^{\mathrm{dlv}}$
      mup_0:  $m^{\mathrm{up}}$
      tau: RTT
    other:
      senders: 1
      qdisc: Drop-tail
      cc_combination: BBR2
      switch_buffer: 0.5
      source_latency_range: [5.0, 10.0]

  trace_RED:
    model_results: True
    experiment_results: True
    metrics: [x_0, q, p, tau]
    smoothed_metrics: [x_0]
    paper_version: True
    legend: True
    legend_bottom: False
    legend_keys:
      y: Rate
      x_0: Rate
      q: Queue
      p: Loss
      v_0: Inflight
      whi_0: $w^{\mathrm{hi}}$
      wlo_0: $w^{\mathrm{lo}}$
      mifl_0: $m^{\mathrm{ifl}}$
      tstr_0: Start time
      xmax_0: $x^{\max}$
      xbtl_0: $x^{\mathrm{btl}}$
      xdel_0: $x^{\mathrm{dlv}}$
      mup_0:  $m^{\mathrm{up}}$
      tau: RTT
    other:
      senders: 1
      qdisc: RED
      cc_combination: BBR2
      switch_buffer: 0.5
      source_latency_range: [5.0, 10.0]

