name: reno_model_checking

# --------------------------------------------------
common_parameters:
  send_duration: 32 #s
  truncate_front: 1 #s
  truncate_back: 2 #s

# --------------------------------------------------
varying_parameters:
  senders: [1]
  link_capacity: [100] # Mbps
  switch_buffer: [1.0] # expressed in BDP of link l
  cc_combination:
    - ['RENO']
  link_latency: [10] # In ms
  source_latency_range: 
    - [5.0, 10.0]
  qdisc:
    - RED
    - Drop-tail

# -------------------------------------------------
model_parameters:
  computation_parameters:
    stp: 0.01 #ms
  trace_parameters:
    plot_trace: True
  analysis_parameters:
    analyze: True

# --------------------------------------------------
experiment_parameters:
  pox_directory: [/home/simon/prog/pox, /home/simonsch/pox/]
  base_config: mininet_experiments/base_config.yaml
  runs: 1

# --------------------------------------------------
plots: []

trace_plots:

  trace_droptail:
    model_results: True
    experiment_results: True
    metrics: [y, q, p, tau, w_0]
    smoothed_metrics: [q]
    paper_version: True
    legend: False
    legend_bottom: False
    legend_keys:
      y: Rate
      q: Queue
      p: Loss
      tau: RTT
      w_0: Cwnd
    other:
      senders: 1
      qdisc: Drop-tail
      cc_combination: RENO
      switch_buffer: 1.0
      source_latency_range: [5.0, 10.0]

  trace_RED:
    model_results: True
    experiment_results: True
    metrics: [y, q, p, tau, w_0]
    paper_version: True
    legend: True
    legend_bottom: False
    legend_keys:
      y: Rate
      q: Queue
      p: Loss
      tau: RTT
      w_0: Cwnd
    other:
      senders: 1
      qdisc: RED
      cc_combination: RENO
      switch_buffer: 1.0
      source_latency_range: [5.0, 10.0]
